### ISSUE TITLE
TLS fatal alert bad_certificate(42) - empty extension sequence found

### ISSUE THREAD

**Issue by mondain** [paullouisageneau/libdatachannel#1182]
I was doing some recent testing with the latest OBS (which of course uses **libdatachannel**) and I've run into an issue with the certificate being provided; My server is alerting that the certificate contains an empty extension sequence. Is this easy to resolve, might I provide my own certificate paths for use, what would you suggest?

```
WARN BCDtlsControlImpl - Connect exception
org.bouncycastle.tls.TlsFatalAlert: bad_certificate(42)
	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCertificate.parseCertificate(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCertificate.<init>(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCrypto.createCertificate(Unknown Source)
	at org.bouncycastle.tls.Certificate.parse(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.receiveServerCertificate(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.processServerCertificate(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.clientHandshake(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.connect(Unknown Source)
	at BCDtlsControlImpl.lambda$start$0(BCDtlsControlImpl.java:254)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: empty extension sequence found
	at org.bouncycastle.asn1.x509.Extensions.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.Extensions.getInstance(Unknown Source)
	at org.bouncycastle.asn1.x509.TBSCertificate.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.TBSCertificate.getInstance(Unknown Source)
	at org.bouncycastle.asn1.x509.Certificate.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.Certificate.getInstance(Unknown Source)
	... 14 common frames omitted
```

**Comment by paullouisageneau** [comment]
libdatachannel in OBS uses MbedTLS as crypto backend, so this could be an issue with [MbedTLS certificate generation](https://github.com/paullouisageneau/libdatachannel/blob/447fd6c288f3ac6a46d49b5430be03290b74e2b1/src/impl/certificate.cpp#L256).

@Sean-Der Does it ring a bell?

**Comment by mondain** [comment]
@paullouisageneau @Sean-Der thanks for looking into this; the bouncy castle team resolved it on their end.
