### ISSUE TITLE
Set the interval for sending key frames

### ISSUE THREAD

**Issue by Fung-blog** [paullouisageneau/libdatachannel#760]
When I was using libdatacahnnel, I found that only one key frame was sent. After packet loss, the video receiver could only play the first frame (the audio is normal). May I ask how to set parameters to solve this problem
![6f62ddb2f2961e07c212df9a099ee74](https://user-images.githubusercontent.com/80746784/204124013-040bc29f-4345-4810-be87-53a74958941a.jpg)

**Comment by paullouisageneau** [comment]
The key frame interval is an encoder setting, so you have to set it on the encoder outside of libdatachannel.

However, are you sure only one key frame is actually sent? Note that the connection shows continuous very high packet loss over time (about 30%), not just once. That's why playback would be stuck, irrelevant of the number of keyframes.

I'd need more information about your setup, but from the symptoms it looks more like a duplicate of https://github.com/paullouisageneau/libdatachannel/issues/740. Does the issue still happen with last `master`?

**Comment by Fung-blog** [comment]
我使用的是“streamer”，视频是其中的样例，已经使用generate_h264.py编码好的

**Comment by Fung-blog** [comment]
I'm using a "streamer" and the video is the sample, encoded using generate_h264.py

**Comment by Fung-blog** [comment]
I tried the latest `master` and found that the problem was still unresolved

![2微信图片_20221128113906](https://user-images.githubusercontent.com/80746784/204189146-f40686e9-6ecf-4db8-9f86-59f04e280d70.png)

![1微信图片_20221128113832](https://user-images.githubusercontent.com/80746784/204189165-f058ab5c-9971-4877-a1d0-7d410156be60.png)
The keyframe is still only sent once, and if the packet is lost, it cannot be decoded later.

I am using the code in the `streamer` to create an H264 video clip. How do I set the IFRAME INTERVAL?

**Comment by paullouisageneau** [comment]
The keyframe is still only sent once, and if the packet is lost, it cannot be decoded later.

That's not the actual problem here. As you can see on the graphs, the connection experiences very high packet loss: 20K packets are lost while 30K are received, meaning the packet loss rate is roughly 40%. Nothing will play if nearly half of packets are lost. Do you run the example locally or across a network?

> I am using the code in the `streamer` to create an H264 video clip. How do I set the IFRAME INTERVAL?

I think you mean "keyframe interval". The `generate_h264.py` script calls ffmpeg under the hood to encode as h264. You can change the default keyframe interval by modifying the script and adding `-x264opts "keyint=XX"` to the `ffmpeg` command line.

**Comment by paullouisageneau** [comment]
> The keyframe is still only sent once, and if the packet is lost, it cannot be decoded later.

That's not the actual problem here. As you can see on the graphs, the connection experiences very high packet loss: 20K packets are lost while 30K are received, meaning the packet loss rate is roughly 40%. Nothing will play if nearly half of packets are lost. Do you run the example locally or across a network?

> I am using the code in the `streamer` to create an H264 video clip. How do I set the IFRAME INTERVAL?

I think you mean "keyframe interval". The `generate_h264.py` script calls ffmpeg under the hood to encode as h264. You can change the default keyframe interval by modifying the script and adding `-x264opts "keyint=XX"` to the `ffmpeg` command line.

**Comment by paullouisageneau** [comment]
> The keyframe is still only sent once, and if the packet is lost, it cannot be decoded later.

That's not the actual problem here. As you can see on the graphs, the connection experiences very high packet loss: 20K packets are lost while 30K are received, meaning the packet loss rate is roughly 40%. Nothing will play if nearly half of packets are lost. Do you run the example locally or across a network?

> I am using the code in the `streamer` to create an H264 video clip. How do I set the IFRAME INTERVAL?

You mean "keyframe interval". The `generate_h264.py` script calls ffmpeg under the hood to encode as h264. You can change the default keyframe interval by modifying the script and adding `-x264opts "keyint=XX"` to the `ffmpeg` command line.

**Comment by Fung-blog** [comment]
When I use the `generate_h264.py` file, I get the following error
```
sh: 1: ffmpeg: Permission denied
Traceback (most recent call last):
  File "generate_h264.py", line 115, in <module>
    main(sys.argv[1:])
  File "generate_h264.py", line 111, in main
    generate(input_file, output_dir, max_samples, fps)
  File "generate_h264.py", line 68, in generate
    data = H264ByteStream(video_stream_file)
  File "generate_h264.py", line 32, in __init__
    with open(file_name, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '_video_stream.h264'
```
I did not find _video_stream.h264 in the original file, what is it and how to solve this error？
